### ISSUE TITLE
翻译方法改进

### ISSUE THREAD

**Issue by kayanouriko** [Bistutu/FluentRead#10]
> 持续按住快捷键，鼠标滑动至文本进行翻译。

基于第二种方式, 当某段话过长占据较大区域的时候, 长按快捷键鼠标在此段落内移动的时候会在译文和原文之间鬼畜的互转, 这在一篇拥有大量段落文章中是极有可能触发的, .

1. 可以加入判断进入第二种方式的时候, 全部文本只进行译文翻译, 不在回滚原文, 但是这样的回滚原文只能通过第一种方式一个个回滚了.
2. 可以加入类似 uBlock Origin 的元素选择器模式, 通过快捷组合键激活该模式, 选中一个区域然后翻转该区域内全部文本的翻译/回滚原文状态, 感觉更好一点.

**Comment by Bistutu** [comment]
关于“鬼畜的互转”的情况，在开发时注意到了，目前设置的防抖时间是250毫秒，也就是如果你在250毫秒快速按下两次快捷键，只会生效一次。
在目前的程序设计中，个人倾向于第一种方式或者添加一个“高级配置”，把这个“防抖时间”的设置权交给用户，自行设置。

**Comment by kayanouriko** [comment]
> 也就是如果你在250毫秒快速按下两次快捷键，只会生效一次。

我说的并不是这种情况.

> 持续按住快捷键，鼠标滑动至文本进行翻译。

说的是我按住快捷键不松, 鼠标移动翻译的情况.

https://github.com/Bistutu/FluentRead/assets/16263287/01eee504-37cc-4287-a55a-32acd17f7251

如视频所示, 我是按住 ctrl 不松, 移动鼠标操作的, 意在翻译全部段落. 但是如果鼠标不在默认防抖的 250 毫秒内移动到下一个未翻译的段落, 就会出现鬼畜互转的情况, 演示的段落文本还算是比较短, 如果有个大段落文本占据了可视区域的一半时候, 感觉不是设置防抖可以解决的.

我是感觉第二种方式是最好的, 这扩展的主要功能很好, 可以适用于那些不需要整页翻译偶尔需要翻译某个段落的情况, 但是别的情况比如指定网站整页翻译/区域翻译, 这扩展目前应对不了或者说使用起来麻烦, 只能借助别的翻译扩展, 但是开着两个翻译扩展又感觉有点臃肿.

当然我只是建议, 还是感谢开发.
