### ISSUE TITLE
可以增加Google翻译么

### ISSUE THREAD

**Issue by hardway** [Bistutu/FluentRead#11]
归属于机器翻译部分，其实Google翻译也是不用API可以免费使用的

比如: https://translate.google.com/translate_a/single?client=it&dt=qca&dt=t&dt=rmt&dt=bd&dt=rms&dt=sos&dt=md&dt=gt&dt=ld&dt=ss&dt=ex&otf=2&dj=1&hl=en&ie=UTF-8&oe=UTF-8&sl=auto&tl=zh-CN&q=hello+world

**Comment by Bistutu** [comment]
Google免费的翻译不支持翻译 HTML 格式的文本，这样会网页原有格式，目前还没有计划接入
