### ISSUE TITLE
百度翻译也支持API

### ISSUE THREAD

**Issue by hardway** [Bistutu/FluentRead#13]
而且每月前100万字免费

https://fanyi-api.baidu.com/product/112

**Comment by Bistutu** [comment]
这个应该是可以的，我先记录下

**Comment by forMyReason** [comment]
如果没有AI的token，使用百度翻译比微软翻译的会好不少

**Comment by Bistutu** [comment]
目前代码已支持使用百度翻译api，但是暂时还未上架应用商店，如果希望尽快体验百度翻译可下载源代码自己编译 `pnpm run zip`，本 issue 终结。
<img width="332" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/f00e4206-b86d-4bce-af66-dcafc6f06456">
