### ISSUE TITLE
小白有个问题，现在GPT不用登录了是不是可以不需要api key了，利用网页访问的那种方式里获取返回

### ISSUE THREAD

**Issue by wfnian** [Bistutu/FluentRead#14]
小白有个问题，现在GPT不用登录了是不是可以不需要api key了，利用网页访问的那种方式里获取返回

**Comment by Bistutu** [comment]
可以的，目前github上有很多这样的开源工具（如https://github.com/missuo/FreeGPT35），你可以把他们部署起来，然后在流畅阅读中使用代理模式。
<img width="346" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/dc0d7d88-a885-4631-80d5-caff810b17b8">
