### ISSUE TITLE
基于GeminiPro翻译失败

### ISSUE THREAD

**Issue by popvlovs** [Bistutu/FluentRead#15]
插件中使用如下配置
```
翻译服务：Gemini
token令牌：MY_TOKEN
模型：gemini-pro

高级选项：
- 代理地址：127.0.0.1:7890
```
触发翻译后无响应，一段时间后超时

我使用的gemini api-token通过如下验证方式验证可用：

```
curl -H 'Content-Type: application/json' -d '{"contents":[{"parts":[{"text":"Write a story about a magic backpack"}]}]}'   -X POST 'https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent?key=MY_TOKEN' -x 127.0.0.1:7890
```

**Comment by Bistutu** [comment]
抱歉，我看了下代码，目前 Gemini 中的确没有使用代理地址，这不是你的问题。我会在下个版本修复！
<img width="1091" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/c72f45f2-38ab-45c3-afd2-8f96b24d8060">

**Comment by Bistutu** [comment]
如果你是用clash的话，一般可以不用配置代理。

<img width="352" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/a5b49251-ff22-4eab-ab49-5c7b5371412e">

**Comment by popvlovs** [comment]
多谢解答，期待版本更新

**Comment by Bistutu** [comment]
我感到非常抱歉。目前提议的方案较难以实现，因为浏览器环境并不直接支持配置代理。

不过其实要实现使用代理很简单，在本机配置就行，我这里可以举个例子🌰：

```shell
# clash规则，新增 generativelanguage.googleapis.com 走代理
rules:
  - DOMAIN-SUFFIX,generativelanguage.googleapis.com,{{国外规则名称}}
```
如：
```shell
rules:
  - DOMAIN-SUFFIX,generativelanguage.googleapis.com,🔰国外流量
```
