### ISSUE TITLE
本地如何调试

### ISSUE THREAD

**Issue by lyd-coding** [Bistutu/FluentRead#17]
想要排查一下本地部署的ollama大模型为何不能调用，拉下来源码，不知道怎么本地调试，可以指点一下吗

**Comment by Bistutu** [comment]
在这个package.json文件里，一般是 `npm dev` 后会自动打开一个调试环境（浏览器）
<img width="397" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/c66f5c61-d0c3-4886-ad7c-a40d16a737c6">

**Comment by Bistutu** [comment]
还有2个注意点：
1. 查看content.js脚本的话，直接打开浏览器的开发者窗口就行
2. 查看 background.js脚本的话，xu需要打开插件的菜单页面，然后在菜单页右键，选择`检查`
<img width="388" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/1dcb4b75-f86a-44f5-be56-59f5c911a52b">
