### ISSUE TITLE
在多段文字中，会出现仅翻译第一段后不再翻译情况

### ISSUE THREAD

**Issue by DaPoHou** [Bistutu/FluentRead#18]
像Kunane Forum论坛，如果是多个段落。只有第一个段落会被翻译，其他段落始终不会被翻译（按住快捷键、鼠标悬停没有任何反应）。

**Comment by Bistutu** [comment]
可以提供下论坛的地址吗，，

**Comment by DaPoHou** [comment]
https://www.webtrees.net/index.php/forum/2-open-discussion/38927-huge-percentage-of-users-never-come-back#105340

**Comment by Bistutu** [comment]
因为HTML5的格式是宽松的，所以即使插件兼容了大部分网站，也还是会有部分网站没有考虑到，目前这部分只能靠对“特定网站”增加“特定规则”来解决。刚看了下，下个版本估计解决

**Comment by DaPoHou** [comment]
感谢！对国外、国内比较流行的论坛程序、问答程序、blog程序，我帮忙多测试测试。
另外，可以考虑不按快捷键，直接鼠标操作（比如双击）触发翻译是不是更好。

**Comment by Bistutu** [comment]
> 感谢！对国外、国内比较流行的论坛程序、问答程序、blog程序，我帮忙多测试测试。 另外，可以考虑不按快捷键，直接鼠标操作（比如双击）触发翻译是不是更好。

会考虑这个建议，可以作为“可选项”加入。

**Comment by Bistutu** [comment]
1、已适配该网站，添加了鼠标双击翻译的功能。
2、目前代码已经推上github，但是版本发布可能要等1-2星期，因为浏览器插件发布需要审核+攒一波再发布新版本，如果老哥有能力的话可以自己编译、安装。项目拉下来，执行 `pnpm build` 就会生成插件的 `.zip`安装包。

<img width="338" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/dea43480-b866-4884-ad29-394b511d15fa">

**Comment by Bistutu** [comment]
Chrome、Firefox 应用商店已经更新，Edge 应用商店正在审核..
<img width="433" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/5095e6d4-0c93-42cd-b094-44284fad4a10">

<img width="564" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/b5e5b3ec-ce44-4e5e-aca2-941e90152904">
