### ISSUE TITLE
有没有机会接入new-api或者one-api

### ISSUE THREAD

**Issue by YonQua** [Bistutu/FluentRead#19]
有没有机会接入new-api或者one-api

**Comment by Bistutu** [comment]
周末see see

**Comment by Bistutu** [comment]
新增了“⭐️自定义接口”模式，已经支持new-api或one-api，待1-2星期后版本更新
<img width="337" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/5026523f-0c6d-4013-a4b1-a07634f330c2">

**Comment by Bistutu** [comment]
Chrome、Firefox 应用商店已经更新，Edge 应用商店正在审核..
<img width="433" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/5095e6d4-0c93-42cd-b094-44284fad4a10">

<img width="564" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/b5e5b3ec-ce44-4e5e-aca2-941e90152904">
