### ISSUE TITLE
匹配网址的限制

### ISSUE THREAD

**Issue by qhq** [Bistutu/FluentRead#2]
因为代码有支持的网站列表，那是否可以match仅匹配这些站点，而不是全网启用。
虽然开销不大，主要个人不是很喜欢所有网站都会启用不适用的脚本。
个人一点小想法，不喜勿喷。

**Comment by Bistutu** [comment]
所有网站通用是基于我当初的设想，AI翻译+Google机翻，目前机翻功能还没有做。抱歉给你带来了困扰，不过如果你愿意的话，可以自己修改下油猴脚本的适配规则，我在下面给出了目前我 README 中所包含的网站，你把这些规则粘贴进去，替代原先的 `@match *://*/*` 规则即可。

```javascript
// @match        *://openai.com/*
// @match        *://chat.openai.com/*
// @match        *://hub.docker.com/*
// @match        *://*.docker.com/*
// @match        *://mvnrepository.com/*
// @match        *://stackoverflow.com/*
// @match        *://star-history.com/*
```

如图：

<img width="429" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/ad47eb26-53d4-482e-bdbf-ab47048138f3">

**Comment by Bistutu** [comment]
我会考虑一下你的想法
