### ISSUE TITLE
保留原文，双语对照

### ISSUE THREAD

**Issue by shouda** [Bistutu/FluentRead#20]
能不能有个选项，可以保留原文，让译文出现在原文下方

ai 有时候可能翻译的没那么好，需要对照原文与译文

**Comment by Bistutu** [comment]
Hi朋友，今天正在开发该功能，基本功能已经实现，现在需要优化下体验。估计在未来一两星期内会放出该功能的beta版本
<img width="1217" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/58d62fb5-78a2-4507-9a0f-d6d89e776b8d">

**Comment by Bistutu** [comment]
Chrome、Firefox 应用商店已经更新，Edge 应用商店正在审核..
<img width="433" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/5095e6d4-0c93-42cd-b094-44284fad4a10">

<img width="564" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/b5e5b3ec-ce44-4e5e-aca2-941e90152904">
