### ISSUE TITLE
Gemini翻译失败

### ISSUE THREAD

**Issue by jeshs** [Bistutu/FluentRead#21]
1、设置了Gemini翻译
![image](https://github.com/Bistutu/FluentRead/assets/43285002/6c6c4a4d-2863-417c-b134-578550e959e5)

2、使用时，提示“Error: Failed to fetch”。是我的设置有问题吗

**Comment by jeshs** [comment]
还有个问题，设置 gemini-1.5-pro 和 gemini-flash-1.5 这两个模型会提示“model 模型设置错误，请前往设置页检查”
![image](https://github.com/Bistutu/FluentRead/assets/43285002/429379a3-bcd1-4602-87ca-1c5400da1abc)

**Comment by Bistutu** [comment]
目前gemini模式不推荐填写代理，我这边gemini-pro模型是可以用的。gemini-1.5-pro 和 gemini-flash-1.5 的确存在问题，应该是bug，谢谢反馈

**Comment by Bistutu** [comment]
已修复，下周跟随下一个版本发布
