### ISSUE TITLE
如何在Edge浏览器中启用双语模式？

### ISSUE THREAD

**Issue by DFVSQY** [Bistutu/FluentRead#23]
没有找到插件的选项，也没有看到双语开光，请作者告知如何开启双语模式？

**Comment by Bistutu** [comment]
提交到应用商店需要审核。目前chrome、firefox已经更新完毕，edge应用商店还在审核中，edge官方给出的时间是一星期左右。
<img width="91" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/b4e8460c-a113-4a50-b581-5d1c5f9fdab8">

**Comment by DFVSQY** [comment]
多谢作者的回答。

**Comment by Bistutu** [comment]
edge商店已更新
