### ISSUE TITLE
是否支持百度ENRIE Speed大模型？

### ISSUE THREAD

**Issue by DFVSQY** [Bistutu/FluentRead#24]
百度的ENRIE Speed宣布免费了，是否可以在插件中使用该大模型进行翻译？

**Comment by Bistutu** [comment]
感谢提议。已添加ERNIE-Speed-8K，下周更新

**Comment by DFVSQY** [comment]
还有一个ERNIE-Speed-128K版本的，作者也一起添加了吧。

**Comment by Bistutu** [comment]
> 还有一个ERNIE-Speed-128K版本的，作者也一起添加了吧。

已接入，不过感觉 ERNIE-Speed-128K 模型目前并没有开放使用，提示次数上限。

```shell
{"error_code":17,"error_msg":"Open api daily request limit reached"}% 
```

**Comment by Bistutu** [comment]
已支持，关闭issue
