### ISSUE TITLE
支持自定义 ChatGPT API 接口地址

### ISSUE THREAD

**Issue by mpbizn** [Bistutu/FluentRead#3]
这个功能后续会考虑加入吗

**Comment by Bistutu** [comment]
这个功能实现起来相对简单，如果最近有更新的话，下个版本就会加入

**Comment by Bistutu** [comment]
@mpbizn 考虑到浏览器安全问题，目前打算只支持 cloudflare 代理 ChatGPT API 接口的模式。
或者还有其他比较靠谱的ChatGPT API 代理地址吗？

**Comment by mpbizn** [comment]
> @mpbizn 考虑到浏览器安全问题，目前打算只支持 cloudflare 代理 ChatGPT API 接口的模式。 或者还有其他比较靠谱的ChatGPT API 代理地址吗？

[https://github.com/chatanywhere/GPT_API_free](url)目前正在用的一个，非常稳定。

**Comment by Bistutu** [comment]
更新插件至最新版即可使用：https://greasyfork.org/zh-CN/scripts/482986-%E6%B5%81%E7%95%85%E9%98%85%E8%AF%BB

<img width="541" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/7e490b8c-47bd-49ec-8b2d-ae50da692a53">

**Comment by mpbizn** [comment]
更换api报错，以更新了最新脚本
浏览器版本:Brave 1.65.6 Chromium:122.0.6261.43(正式版本)nightly(64位)
Tampermonkey版本:5.0.1
脚本版本:1.12
![Snipaste_2024-02-17_15-31-46](https://github.com/Bistutu/FluentRead/assets/55294216/e331e577-d7ba-4a68-80de-2457f194525d)
![Snipaste_2024-02-17_16-36-19](https://github.com/Bistutu/FluentRead/assets/55294216/d9145769-c65f-454f-86d0-cffab3fedab7)

**Comment by Bistutu** [comment]
> 更换api报错，以更新了最新脚本 浏览器版本:Brave 1.65.6 Chromium:122.0.6261.43(正式版本)nightly(64位) Tampermonkey版本:5.0.1 脚本版本:1.12 ![Snipaste_2024-02-17_15-31-46](https://private-user-images.githubusercontent.com/55294216/305627997-e331e577-d7ba-4a68-80de-2457f194525d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjc0ODEsIm5iZiI6MTcwODIyNzE4MSwicGF0aCI6Ii81NTI5NDIxNi8zMDU2Mjc5OTctZTMzMWU1NzctZDdiYS00YTY4LTgwZGUtMjQ1N2YxOTQ1MjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAzMzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYjAwNmY2ZGQ0ZjEyYzUwYmM4YjRjOGIzZWRhODBkMmM2Mzk0M2E2ZjFlM2I3NDU0ODFmZmU5NGE1YTQ0OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mT9Vd1aJaIBjOyXRMRzESGFRJnecassyPStKrRv7pUk) ![Snipaste_2024-02-17_16-36-19](https://private-user-images.githubusercontent.com/55294216/305628982-d9145769-c65f-454f-86d0-cffab3fedab7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyMjc0ODEsIm5iZiI6MTcwODIyNzE4MSwicGF0aCI6Ii81NTI5NDIxNi8zMDU2Mjg5ODItZDkxNDU3NjktYzY1Zi00NTRmLTg2ZDAtY2ZmYWIzZmVkYWI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDAzMzMwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlNTkyOTFiOTJjNmFjNmRiZjc0MzVlYTEyZjZmZTE2OWY1NmI1ZDdmMzBkOGRiZDAwNzQ1ZDJmNTAxODMwODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.t6HjamDbX7EPQcwpgEJX8jc0b7OH8tOS_NW-Wq_U8oc)

# 这个地址：https://api.chatanywhere.com.cn/v1/chat/completions
