### ISSUE TITLE
希望支持移动设备的翻译操作

### ISSUE THREAD

**Issue by him007** [Bistutu/FluentRead#4]
当前的两种翻译操作都需要快捷键和鼠标，在手机、平板上都不支持，安卓版firefox+篡改猴、X浏览器可以导入但是使用不了

**Comment by Bistutu** [comment]
这两天一直在寻找一种解决方案，如果有机会的话，会在后面的版本中推出！

**Comment by mpbizn** [comment]
> 这两天一直在寻找一种解决方案，如果有机会的话，会在后面的版本中推出！

firefox nightly可以正常用，就是ui需要适配一下

**Comment by mpbizn** [comment]
> 这两天一直在寻找一种解决方案，如果有机会的话，会在后面的版本中推出！

[https://greasyfork.org/zh-CN/scripts/340-popup-search](url)，可以参考一下这个脚本，在安卓Firefox Nightly上选择好要复制的文本后再点一下选中就有功能弹窗了

**Comment by imaqine** [comment]
> 新版本中已经支持移动端操作，`三指同时触摸`屏幕可以触发翻译，前提是浏览器支持油猴脚本：[安装地址](https://greasyfork.org/zh-CN/scripts/482986-%E6%B5%81%E7%95%85%E9%98%85%E8%AF%BB/stats)

请问怎么翻译整页内容啊，三指操作只翻译手指按的地方，我想要全页翻译

**Comment by imaqine** [comment]
> 新版本中已经支持移动端操作，`三指同时触摸`屏幕可以触发翻译，前提是浏览器支持油猴脚本：[安装地址](https://greasyfork.org/zh-CN/scripts/482986-%E6%B5%81%E7%95%85%E9%98%85%E8%AF%BB/stats)

还有一个问题，三指同时触摸，时间稍长久触发手机自带的三指截图功能

**Comment by imaqine** [comment]
> 新版本中已经支持移动端操作，`三指同时触摸`屏幕可以触发翻译，前提是浏览器支持油猴脚本：[安装地址](https://greasyfork.org/zh-CN/scripts/482986-%E6%B5%81%E7%95%85%E9%98%85%E8%AF%BB/stats)

好像手机油猴版不能双语显示
