### ISSUE TITLE
Genimi 是否可以支持自定义API接口地址

### ISSUE THREAD

**Issue by outcastveron** [Bistutu/FluentRead#5]

**Comment by Bistutu** [comment]
支持的🙋🏻‍♂️不过由于浏览器的一些安全特性，我需要把api接口地址写到代码里面，你有合适的地址吗❓

**Comment by outcastveron** [comment]
地址是自己搭建的，那么请问如何在脚本中修改呢？

**Comment by Bistutu** [comment]
你可以在评论中回复，我会在下一个版本中添加进去

**Comment by hotraygroup** [comment]
![image](https://github.com/Bistutu/FluentRead/assets/3041120/2384c2e8-277c-4ef0-910c-10ed9e95b354)

**Comment by Bistutu** [comment]
> ![image](https://private-user-images.githubusercontent.com/3041120/309677380-2384c2e8-277c-4ef0-910c-10ed9e95b354.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDE5OTAsIm5iZiI6MTcwOTU0MTY5MCwicGF0aCI6Ii8zMDQxMTIwLzMwOTY3NzM4MC0yMzg0YzJlOC0yNzdjLTRlZjAtOTEwYy0xMGVkOWU5NWIzNTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDRUMDg0MTMwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDMyZmVhMzQzMmViOTY1ZTQwY2FhYzY5YTc0NjY5YTZkZDM5NTE1NDUyMGYxZTEwNTg3Y2VlNjlkMDU0M2MzYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.FC_xN3LxKRkkxg0hyDbvK0yKrk4UuTfnOT4Bs5f2WIs)

<img width="711" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/cce24b8b-0d5a-4af9-a317-d8efb156521a">

**Comment by hotraygroup** [comment]
服务器是自己搭建的，自己的网址。形如：https://api.ai.xxxxx.com/

**Comment by hotraygroup** [comment]
可以内置好规则，让api地址适应内置规则，是否可行？

**Comment by molezz** [comment]
看起来自定义地址比较复杂，刚想说既然支持了deepl， 那还能支持deeplx的自定义地址……

**Comment by hiforrest** [comment]
ChatGPT 也不能用第三方的 API 地址，期待解决这个问题

**Comment by Bistutu** [comment]
插件已经重构成浏览器可以直接安装的插件，安装新版插件支持自定义任何API接口地址，见：[安装指南](https://github.com/Bistutu/FluentRead?tab=readme-ov-file#%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97)，本 issue 终结。
<img width="610" alt="image" src="https://github.com/Bistutu/FluentRead/assets/91378285/cef1a3eb-90d5-459a-a335-352e254d3df2">
