### ISSUE TITLE
翻译报错

### ISSUE THREAD

**Issue by Houtx** [Bistutu/FluentRead#7]
选择的微软翻译

![image](https://github.com/Bistutu/FluentRead/assets/17922172/c4fad97f-f7a2-4d2e-915b-4f384dd096b3)

![image](https://github.com/Bistutu/FluentRead/assets/17922172/265bbdc4-95f7-4455-a5f0-ce7075042088)

**Comment by Bistutu** [comment]
这个错误还在持续吗？😨

**Comment by Houtx** [comment]
> 这个错误还在持续吗？😨

已经恢复了
